import { MigrationInterface, QueryRunner } from "typeorm";

export class Users1728601761706 implements MigrationInterface {
    name = 'Users1728601761706'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "firstname" character varying(250) NOT NULL, "lastname" character varying(250) NOT NULL, CONSTRAINT "unique_fullname" UNIQUE ("firstname", "lastname"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "firstname_index" ON "users" ("firstname") `);
        await queryRunner.query(`CREATE INDEX "lastname_index" ON "users" ("lastname") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."lastname_index"`);
        await queryRunner.query(`DROP INDEX "public"."firstname_index"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
