services:
  database:
    container_name: database
    image: postgres:16-bookworm
    restart: always
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 10s
      timeout: 30s
      retries: 10
      start_period: 30s
      start_interval: 2s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    volumes:
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - data:/var/lib/postgresql/data