services:
  database:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - data:/var/lib/postgresql/data